import { ReduxProvider } from '@/store/provider'
import { Kanit } from 'next/font/google'
import './globals.css'

const kanit = Kanit({
  variable: '--font-kanit',
  subsets: ['latin'],
  weight: ['400', '700'],
})

export const metadata = {
  title: 'Auto',
  description: 'Generated by create next app', 
}

export default function RootLayout({ children }) {

  return (
    <html lang="en">
      <body
        className={`${kanit.variable} antialiased`}
      >
        <ReduxProvider>
          {children}
        </ReduxProvider>
      </body>
    </html>
  )
}
