import { Kanit } from 'next/font/google'

import '../globals.css'
import Footer from '@/components/Footer'
import ShopNavbar from '@/components/shop/ShopNavbar'

const kanit = Kanit({
  variable: '--font-kanit',
  subsets: ['latin'],
  weight: ['400', '700'],
})

export const metadata = {
  title: 'SHOP I Auto',
  description: 'Generated by create next app', 
}

export default function RootLayout({ children }) {

  return (
    <html lang="en">
      <body
        className={`${kanit.variable} antialiased`}
      >
          <ShopNavbar />
          {children}
          <Footer/>
      </body>
    </html>
  )
}